### ISSUE TITLE
Needed the current hash

### ISSUE THREAD

**Issue by gilescope** [sagiegurari/git_info#4]
Hi I wanted the last commit sha and shortend commit sha.

- thanks for the work btw!

**Comment by sagiegurari** [comment]
cool. will check it out.

**Comment by sagiegurari** [comment]
done and released in version 0.1.2
thanks a lot for the feedback.

```rust
    println!(
        "Last Commit Hash: {}",
        info.head.last_commit_hash.unwrap_or("Unknown".to_string())
    );
    println!(
        "Last Commit Hash (short): {}",
        info.head
            .last_commit_hash_short
            .unwrap_or("Unknown".to_string())
    );
```

**Comment by gilescope** [comment]
Thanks, will give it a go this evening.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gilescope** [comment]
Works a treat - thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sagiegurari** [comment]
thanks for validating
